# Generated by Django 5.2.5 on 2025-10-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinome', models.CharField(max_length=50, unique=True)),
                ('nome_real', models.CharField(blank=True, max_length=100, null=True)),
                ('poder_principal', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('historia', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos_herois/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
